service: stone-challenge
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  environment: ${file(env.json)}
  stage: ${file(env.json):STAGE}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - 'arn:aws:dynamodb:${opt:region, file(env.json):AWS_CONFIG_REGION}:*:table/${file(env.json):DYNAMO_DB_TABLE}'
            - 'arn:aws:dynamodb:${opt:region, file(env.json):AWS_CONFIG_REGION}:*:table/${file(env.json):DYNAMO_DB_TABLE}/index/*'

functions:
  create-user:
    handler: src/functions/users/create-user-function.handler
    events:
      - httpApi:
          path: /users
          method: post
  get-user:
    handler: src/functions/users/get-user-function.handler
    events:
      - httpApi:
          path: /users/{id}
          method: get
  increment-visit:
    handler: src/functions/visits/increment-visit-function.handler
    events:
      - httpApi:
          path: /visits
          method: put
  get-visits:
    handler: src/functions/visits/get-visits-function.handler
    events:
      - httpApi:
          path: /visits
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-typescript

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${file(env.json):DYNAMO_DB_TABLE}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: localId1
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        LocalSecondaryIndexes:
          - IndexName: LocalId1Index
            KeySchema:
              - AttributeName: pk
                KeyType: HASH
              - AttributeName: localId1
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
